# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:   

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      id: id1
      uses: actions/setup-java@v3
      with:
        java-version: ''
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      id: id2
      run: mvn -B package --file pom.xml      
    - name: Notify dedicated teams channel
      if: always()
      uses: jdcargile/ms-teams-notification@v1.3
      with:
        if: steps.id1.outcome == 'success' || steps.id2.outcome == 'success'
        github-token: ${{ github.token }} # this will use the runner's token.
        ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        notification-summary: Build is sucessful!! 
        notification-color: 28a745
        timezone: America/Denver
        if: steps.id1.outcome != 'success' || steps.id2.outcome != 'success'
        github-token: ${{ github.token }} # this will use the runner's token.
        ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        notification-summary: Build is sucessful!! 
        notification-color: 28a745
        timezone: America/Denver        

    # - name: Notify dedicated teams channel
    #   if: always()
    #   if: steps.id1.outcome != 'success' || steps.id2.outcome != 'success'  
    #   uses: jdcargile/ms-teams-notification@v1.3
    #   with:
    #     github-token: ${{ github.token }} # this will use the runner's token.
    #     ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
    #     notification-summary: Build Failed!! 
    #     notification-color: dc3545
    #     timezone: America/Denver 
    #     run: exit 1