name: Testif
on:
  pull_request:
    types:    [ opened, closed ]
    branches: [ main ]
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: testif
      #if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
      if: github.event.pull_request.merged == true
      run: echo "Hi i am executed"  
    
