name: Testif
on:
  workflow_dispatch:   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: testif
      if: github.event.pull_request.merged == true
      run: echo "Hi i am executed"  
    
